# export LANG=ja_JP.UTF-8

eval "$(/usr/local/bin/brew shellenv)"
. /usr/local/opt/asdf/libexec/asdf.sh

eval "$(direnv hook zsh)"

export PATH=$PATH:$HOME/go/bin

export GOPATH=$HOME/go

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi

alias ls=exa
alias fd=find
alias bat=cat
alias g='cd $(ghq root)/$(ghq list | peco)'

alias ll="ls -la"

setopt PROMPT_SUBST
source ~/.zsh/.git-prompt.sh

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
PROMPT='%F{cyan}%*%f: %F{green}%~%f %F{red}$(__git_ps1 "(%s)" )%f 
 -> '

