export LANG=ja_JP.UTF-8

eval "$(/opt/homebrew/bin/brew shellenv)"
. /opt/homebrew/opt/asdf/libexec/asdf.sh

export PATH=$PATH:$HOME/go/bin

export GOPATH=$HOME/go

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi

alias ls=exa
alias fd=find
alias bat=cat
alias g='cd $(ghq root)/$(ghq list | peco)'

alias ll="ls -la"

setopt PROMPT_SUBST
source ~/.zsh/.git-prompt.sh

export GIT_PS1_SHOWDIRTYSTATE=true
PROMPT='%F{cyan}%*%f: %F{green}%~%f %F{red}$(__git_ps1 "%s" )%f 
 -> '

git config --global alias.sw 'switch'
git config --global alias.pH 'push origin HEAD'
git config --global alias.co 'checkout'
git config --global alias.rema 'rebase origin/master'

